#!/usr/bin/env python3
"""
cleanup_storage.py -- shrink outputs already written by Screen_Cutouts_Pipeline.py, in place.

    python cleanup_storage.py [BASE_DIR]              # dry run: report what would be saved
    python cleanup_storage.py [BASE_DIR] --apply      # do it
    python cleanup_storage.py [BASE_DIR] --apply --delete-old   # also delete old_* / aggressive_old_* folders

Per detector folder <BASE_DIR>/<fits>/<det>/ (and its aggressive/ subfolder):
  euclid_masks/   all .npy maps -> one compressed masks.npz (~50-100 kB instead of ~45 MB);
                  per-class mask .npy/.png and classified_overlay.png removed;
                  classified_overlay_legend.png -> .jpg
  QA images       <id>_DET<nn>.png, *_sam_boxes*.png, *_screened*.png -> .jpg (q85, ~4x smaller)
                  *_dispersion_frame.png removed (regenerated by any rerun)
  cutouts/        per-cutout <stem>_bbox.npy / _points.npy / _dark.npy -> one boxes_<id>_DET<nn>.npz
                  per detector (cutout_boxes.py; ~3 fewer files per cutout); the cutout images stay
  comparisons     .npy copies in dropped_by_aggressive/ and only_in_aggressive/ removed (the
                  originals stay in cutouts/); previews beyond --max-previews (default 50) removed
Detector folders from older runs (e.g. without euclid_masks/) are fine: missing pieces are skipped.
--no-bundle keeps the per-cutout box files (the ORIGINAL SAM / PreContSub scripts need them);
--keep-png keeps the boxed detector image as PNG.
Never touched: *_noboxes.png (used by a later step), the cutout images in cutouts/ (SAM input), detections / screened_out CSVs, run_info.json,
sam_results*/ (only reported). old_* folders are only deleted with --delete-old.
"""
import os, re, sys, glob, shutil, argparse
import numpy as np
from PIL import Image
from cutout_boxes import save_boxes, load_boxes

MAPS = ('label_map', 'artifact_type_map', 'compact_sources', 'zo_candidates', 'footprint')


def size(path):
    """Space actually used on disk (whole blocks), not just the bytes in the file."""
    du = lambda p: os.stat(p).st_blocks * 512
    if os.path.isfile(path): return du(path)
    return sum(du(os.path.join(r, f)) for r, _, fs in os.walk(path) for f in fs)


def human(n):
    for u in ('B', 'kB', 'MB', 'GB', 'TB'):
        if n < 1024: return f"{n:.1f} {u}"
        n /= 1024
    return f"{n:.1f} PB"


class Plan:
    def __init__(self, apply): self.apply, self.saved, self.files_removed = apply, 0, 0

    def remove(self, p):
        self.saved += size(p)
        if self.apply:
            shutil.rmtree(p) if os.path.isdir(p) else os.remove(p)

    def to_jpg(self, png):
        jpg = png[:-4] + '.jpg'
        before = size(png)
        if self.apply:
            Image.open(png).convert('RGB').save(jpg, quality=85)
            self.saved += before - size(jpg); os.remove(png)
        else:
            self.saved += int(before * 0.7)          # typical saving, estimated in a dry run


def shrink_masks(md, plan):
    npys = {m: os.path.join(md, m + '.npy') for m in MAPS}
    npz = os.path.join(md, 'masks.npz')
    if not os.path.exists(npz) and all(os.path.exists(p) for p in npys.values()):
        if plan.apply:
            np.savez_compressed(npz, **{m: np.load(p) for m, p in npys.items()})
    if os.path.exists(npz) or not plan.apply:
        for p in glob.glob(os.path.join(md, '*.npy')):
            plan.remove(p)
        for p in glob.glob(os.path.join(md, '*_mask.png')) + [os.path.join(md, 'classified_overlay.png')]:
            if os.path.exists(p): plan.remove(p)
    p = os.path.join(md, 'classified_overlay_legend.png')
    if os.path.exists(p): plan.to_jpg(p)


def bundle_boxes(cd, plan):
    """Per-cutout _bbox/_points/_dark files -> one boxes_<id>_DET<nn>.npz per detector."""
    small = glob.glob(os.path.join(cd, '*_bbox.npy')) + glob.glob(os.path.join(cd, '*_points.npy')) \
        + glob.glob(os.path.join(cd, '*_dark.npy'))
    if not small: return 0
    if plan.apply:
        recs = load_boxes(cd)                      # merges an existing boxes_*.npz with the old files
        by_det = {}
        for stem, r in recs.items():
            m = re.match(r'cutout_(.+)_DET(\d\d)_', stem)
            if m: by_det.setdefault((m.group(1), m.group(2)), []).append((stem, r['bbox'], r['points'], r['dark']))
        for (fid, det), rr in by_det.items():
            save_boxes(os.path.join(cd, f"boxes_{fid}_DET{det}.npz"), rr)
        check = load_boxes(cd)
        if not all(s in check for s in recs):      # never delete anything that did not make it in
            print(f"  ! {cd}: bundling incomplete, per-cutout files kept"); return 0
    for p in small: plan.remove(p)
    return len(small)


def shrink_detector(dd, plan, max_previews, bundle=True, keep_png=False):
    cd = os.path.join(dd, 'cutouts')
    if bundle and os.path.isdir(cd): plan.files_removed += bundle_boxes(cd, plan)
    md = os.path.join(dd, 'euclid_masks')
    if os.path.isdir(md): shrink_masks(md, plan)
    for p in glob.glob(os.path.join(dd, '*_dispersion_frame.png')):          # *_noboxes.png is never touched
        plan.remove(p)
    qa = glob.glob(os.path.join(dd, '*_sam_boxes*.png')) + glob.glob(os.path.join(dd, '*_screened*.png'))
    if not keep_png: qa += glob.glob(os.path.join(dd, '*_DET[0-9][0-9].png'))   # the boxed detector image
    for p in qa:
        plan.to_jpg(p)
    for sub in ('dropped_by_aggressive', 'only_in_aggressive'):
        cd = os.path.join(dd, sub)
        if not os.path.isdir(cd): continue
        for p in glob.glob(os.path.join(cd, '*.npy')): plan.remove(p)
        pngs = sorted(glob.glob(os.path.join(cd, '*.png')))
        if max_previews and len(pngs) > max_previews:
            keep = set(np.random.default_rng(0).choice(pngs, max_previews, replace=False))
            for p in pngs:
                if p not in keep: plan.remove(p)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('base_dir', nargs='?', default='.')
    ap.add_argument('--apply', action='store_true', help='actually change files (default: dry run)')
    ap.add_argument('--delete-old', action='store_true', help='delete old_* and aggressive_old_* folders')
    ap.add_argument('--max-previews', type=int, default=50, help='comparison previews kept per folder (0 = all)')
    ap.add_argument('--no-bundle', action='store_true',
                    help="keep per-cutout _bbox/_points/_dark .npy files (needed if you will run the ORIGINAL "
                         "SAM / PreContSub scripts, which cannot read boxes_*.npz)")
    ap.add_argument('--keep-png', action='store_true', help='keep the boxed detector image <id>_DET<nn>.png as PNG')
    a = ap.parse_args()
    base = os.path.abspath(a.base_dir)
    det_dirs = sorted(d for d in glob.glob(os.path.join(base, '*', '[0-9][0-9]')) if os.path.isdir(d))
    if not det_dirs: sys.exit(f"no <fits>/<det>/ folders under {base}")
    print(f"{'APPLYING' if a.apply else 'DRY RUN'} in {base}: {len(det_dirs)} detector folders")
    total_before = sum(size(d) for d in det_dirs)
    plan = Plan(a.apply); old_bytes = 0; sam_bytes = 0; cut_bytes = 0
    for dd in det_dirs:
        for d in [dd] + ([os.path.join(dd, 'aggressive')] if os.path.isdir(os.path.join(dd, 'aggressive')) else []):
            shrink_detector(d, plan, a.max_previews, bundle=not a.no_bundle, keep_png=a.keep_png)
            cut_bytes += size(os.path.join(d, 'cutouts')) if os.path.isdir(os.path.join(d, 'cutouts')) else 0
            sam_bytes += sum(size(p) for p in glob.glob(os.path.join(d, 'sam_results*')))
        for od in glob.glob(os.path.join(dd, 'old_*')) + glob.glob(os.path.join(dd, 'aggressive_old_*')):
            if a.delete_old: plan.remove(od)
            else: old_bytes += size(od)
    print(f"detector folders now:   {human(total_before)}")
    print(f"{'freed' if a.apply else 'would free'}:            {human(plan.saved)}")
    print(f"per-cutout box files {'bundled' if a.apply else 'to bundle'}:  {plan.files_removed} files -> one boxes_*.npz per detector")
    print(f"cutouts/ (kept, SAM input):            {human(cut_bytes)}")
    print(f"sam_results*/ (not touched):           {human(sam_bytes)}")
    if old_bytes:
        print(f"old_* / aggressive_old_* folders:      {human(old_bytes)}  -> add --delete-old to remove them")
    if not a.apply:
        print("Nothing changed. Rerun with --apply to do it.")


if __name__ == '__main__':
    main()
